version: '3'

services:
#  zookeeper:
#    image: zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest 
#    depends_on:
#      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS_EXTERNAL_PORT: 9092
      KAFKA_PROCESS_ROLES: controller,broker  
  mysql:
    image: mysql:8.3.0
    container_name: mysql-8.3.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pPavan@2003"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: 'Pavan@2003'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  auth: 
    image: auth_service
    build: .
    container_name: auth_producer
    environment: 
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    develop:
      watch:
        - path: ./target/auth-0.0.1-SNAPSHOT.jar  # Watch for new JAR files
          action: rebuild            # Rebuild the container when JAR changes
        - path: ./src/main/resources/application.properties
          action: sync               # Just sync files if it's just a config change
          target: /app/resources
  
  usersvc:
    image: user_service
    build: ../usersvc
    container_name: usersvc_consumer
    environment: 
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      
    develop:
      watch:
        - path: ../usersvc/target/consumer-0.0.1-SNAPSHOT.jar  # Watch for new JAR files
          action: rebuild            # Rebuild the container when JAR changes
        - path: ../usersvc/src/main/resources/application.properties
          action: sync               # Just sync files if it's just a config change
          target: /app/resources
  
  
  
volumes:
  mysql-db:
    driver: local